# .github/workflows/build.yml
name: Node Build
run-name: {{ github.actor }} is testing workflow for node js
on:
  push:
    branches:
      - github-actions
  pull_request:
    branches:
      - github-actions
jobs:
  build:
    runs-on: ${{ matrix.os }}
  strategy:
    matrix:
      node-version: [12.x]
      os: [windows-latest]
  steps:
    - uses: actions/checkout@v4
    - name: Run node.js on latest Windows.
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install NPM and build.
      run: |
        npm ci
        npm run build